### ISSUE TITLE
Add ASM compiler support?

### ISSUE THREAD

**Issue by clouds56** [JuliaPackaging/BinaryBuilderBase.jl#161]
Some environment like mingw would like asm compiler such as uasm.
https://github.com/msys2/MINGW-packages/blob/8ff2f8d0c3589b43d538cb6c738a0d9eed7e9d7e/mingw-w64-clang/PKGBUILD#L297-L298
```cmake
      export ASM_COMPILER="${MINGW_PREFIX}/bin/uasm.exe"
      platform_config+=(-DCMAKE_ASM_MASM_COMPILER="${ASM_COMPILER}"
```

**Comment by giordano** [comment]
What kind of support do you need?  Just install the ASM you want and use it?  There are many packages which already do that

**Comment by clouds56** [comment]
Sorry missed that comment, do you mean I could use pacman in Mingw and install any package in the script?

**Comment by giordano** [comment]
Not `pacman` but `apk`, this is an Alpine Linux system: https://docs.binarybuilder.org/stable/build_tips/#Dependencies-for-the-target-system-vs-host-system

**Comment by clouds56** [comment]
Thanks for the information, I successfully install uasm via
```
apk add uasm --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
```
