### ISSUE TITLE
LibraryProduct docstring mentions dir_paths kwarg, but it doesn't exist

### ISSUE THREAD

**Issue by marcom** [JuliaPackaging/BinaryBuilderBase.jl#179]
This should work according to the docstring of LibraryProduct:
`LibraryProduct("libfoo", :libfoo; dir_paths=["lib/plugins"])`

But instead it gives an error.

The undocumented variants `LibraryProduct("libfoo", :libfoo, ["lib/plugins"])` or `LibraryProduct("libfoo", :libfoo, "lib/plugins")` do work.

Should the docstring be changed?

**Comment by giordano** [comment]
> Should the docstring be changed?

I think so, thanks
