### ISSUE TITLE
Support HostBuildDependecies

### ISSUE THREAD

**Issue by vchuravy** [JuliaPackaging/BinaryBuilderBase.jl#37]
For https://github.com/JuliaPackaging/Yggdrasil/pull/1694 it would be useful to be able to download the host version of `LLVM_full_jll` so that I can use `llvm-config` as the `LLVM_CONFIG_HOST` and get the right build flags.

**Comment by giordano** [comment]
This is great idea and relatively easy to implement, but we have one point to decide: where to install these dependencies.  The `${prefix}` is where the target stuff lives.  Any suggestion?

**Comment by vchuravy** [comment]
`${hostprefix}` ;)
