### ISSUE TITLE
ArchiveSource in the tar.zst standard errors 

### ISSUE THREAD

**Issue by musm** [JuliaPackaging/BinaryBuilderBase.jl#75]
On a machine without `zst` installed (`sudo apt install zstd`), `ArchiveSource` fails to extract and the corresponding build script errors without a clue why. I suggest either an error message is spit out or, even better, include this compression standard since `ArciveSource` already accepts `zst`'s.

**Comment by musm** [comment]
https://github.com/JuliaPackaging/BinaryBuilderBase.jl/blob/master/src/Prefix.jl#L278 probably need a `try` `catch`

**Comment by giordano** [comment]
Fixed by #292
