### ISSUE TITLE
Don't print non-errors in red

### ISSUE THREAD

**Issue by musm** [JuliaPackaging/BinaryBuilderBase.jl#76]
Printing this in red is misleading as it makes it look like something errored in the build process

![image](https://user-images.githubusercontent.com/4319522/99119319-05259200-25c7-11eb-88fa-81f62de8dac8.png)

**Comment by giordano** [comment]
I think this is handled by [`OutputCollectors.jl`](https://github.com/JuliaPackaging/OutputCollectors.jl)

**Comment by giordano** [comment]
What you're showing here is not the build process but a copy of the build script, which is purposely written to `stderr`.  The log of the build process is written to the appropriate streams, with appropriate colours
