### ISSUE TITLE
Use -fno-optimize-sibling-calls for Fortran libraries

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPackaging/BinaryBuilderBase.jl#92]
Newer gfortran compilers do more aggressive optimization that breaks the ABI for character arguments.

See https://github.com/JuliaLang/julia/issues/32870 for a detailed description.
And a fix of a crash on power: https://github.com/JuliaLang/julia/pull/38836

One remedy is passing `-fno-optimize-sibling-calls` to gfortran, which will prevent the optimizations that cause breakage. We may at least want to apply this for LAPACK (inside OpenBLAS) and a few other Fortran libraries.

Over time, packages that call fortran functions with character/string inputs should do the right thing.

**Comment by giordano** [comment]
I transferred the issue to BinaryBuilderBase because I thought we may want to do this for all libraries, directly in the compiler wrappers.  But I'm not entirely sure this is the case to be honest :sweat_smile:

**Comment by ViralBShah** [comment]
@vchuravy Would it be a problem to do this by default for all fortran libraries? It seems safe to me to do so.

**Comment by ViralBShah** [comment]
I guess doing it in in BinaryBuilderBase is a good idea, since we can use it in a few builds, and then remove the flag when Julia upstream fixes it. But note that people are probably doing bad things in other non-Julia libraries too.

**Comment by ViralBShah** [comment]
It would be nice to pass this flag directly to gfortran by default, so that it makes its way through all the libraries over time. What needs to happen for this?

**Comment by ViralBShah** [comment]
Given that this really hasn't been much of an issue, I'm closing this.
